name: pixabay_dashboard 
description: A Pixabay image dashboard built with Flutter Web. 
 
publish_to: 'none' 
 
version: 1.0.0+1 
 
  sdk: 3.0.0 <4.0.0 
 
dependencies: 
  flutter: 
    sdk: flutter 
  http: 1.2.2 
  provider: 6.1.2 
 
dev_dependencies: 
  flutter_test: 
    sdk: flutter 
  flutter_lints: 4.0.0 
 
flutter: 
  uses-material-design: true 
